image:
  name: kleinstein/immcantation:test

pipelines:
  branches:
    default:
      - step:
          script:
            - pip3 install hg+https://bitbucket.org/kleinstein/presto#default
            - python3 setup.py install
            - python3 -m unittest
